#! /bin/bash --norc

cd /usr/lib/ccache

suffixList="
gcc
g++
c++
"

prefixList="
arm-none-eabi-
arm-linux-gnueabihf-
x86_64-apple-darwin12-
x86_64-w64-mingw32-
arm-xilinx-eabi-
arm-xilinx-linux-gnueabi-
"

for p in $prefixList; do
	for s in $suffixList; do
		comp="${p}${s}"
		[ ! -f $comp ] && sudo ln -svf ../../bin/ccache $comp
	done
done

cd -

echo "Force use ccache for compiler in /soft ..."
for s in $suffixList; do
	for bin in $(find -L /soft -type f -name "*-$s" 2>/dev/null); do
		if [ ! -f ${bin}.real ]; then
			mv -v $bin{,.real}
			ln -sv $HOME/myenv/tools/ccache-hook $bin
		fi
	done
done

