"-------------------------------------------------------------------------
"Color and font
"-------------------------------------------------------------------------
so $VIMRUNTIME/colors/inkpot.vim

set guifont=Monospace\ 11

" Font
set gfn=Monospace\ 11
