#!/bin/sh

Verbose="n"

echo $@ | grep -- -v > /dev/null
if [ $? -eq 0 ]; then
	Verbose="y"
	set -x
fi

shas=$(echo $@ | sed s@'-v'@@g)

# Gen diff script
TmpDir=$(mktemp -d)
DiffScript=$TmpDir/diff_cmd_script
LocalTreeDir=$TmpDir/LocalTree
RemoteTreeDir=$TmpDir/RemoteTree
DiffStat=$TmpDir/DiffStat

RootDir=$(pwd)

echo "nodiff" > $DiffStat

mkdir $LocalTreeDir $RemoteTreeDir

cat << EOF > $DiffScript
#! /bin/sh

optVer=""

if [ "$Verbose" = "y" ]; then
	set -x
	echo "Args --->"
	echo \$*
	echo "<---"
	optVer="-v"
fi

Filename="\$1"

Local="\$2"
VerLocal="\$3"
Remote="\$5"
VerRemote="\$6"

FileDir=\$(dirname \$Filename)

if [ \$VerLocal  != '.' ]; then
	mkdir -p $LocalTreeDir/\$FileDir
	if [ "\$VerLocal" = "0000000000000000000000000000000000000000" ]; then
		ln -s \$optVer $RootDir/\$Local $LocalTreeDir/\$Filename
	else
		cp -f \$optVer \$Local $LocalTreeDir/\$Filename
	fi
fi

if [ \$VerRemote != '.' ]; then
	mkdir -p $RemoteTreeDir/\$FileDir
	if [ "\$VerRemote" = "0000000000000000000000000000000000000000" ]; then
		ln -s \$optVer $RootDir/\$Remote $RemoteTreeDir/\$Filename
	else
		cp -f \$optVer \$Remote $RemoteTreeDir/\$Filename
	fi
fi

echo "diff" > $DiffStat

EOF
chmod +x $DiffScript

# execute git diff
OldDiffConfig=$(git config diff.external)
unsetGitDiffExternal() {
	if [ "$OldDiffConfig" != "" ]; then
		git config diff.external $OldDiffConfig
	else
		git config --unset diff.external
	fi
}
trap unsetGitDiffExternal INT
git config diff.external $DiffScript
git diff --ext-diff $shas
unsetGitDiffExternal

if [ "$Verbose" = "y" ]; then
	echo "Local tree :"
	tree $LocalTreeDir
	echo ""
	echo "Remote tree :"
	tree $RemoteTreeDir
	echo ""
fi

# Launch bcompare
if [ "$(cat $DiffStat)" != "nodiff" ]; then
	bcompare -expandall -title1="$lTitle" -title2="$rTitle" $LocalTreeDir $RemoteTreeDir | cat
fi

# Remove temp dir
rm -rf $TmpDir
set +x
