#!/bin/bash

[ "$1" = '-v' ] && set -x

tmpRootDir=.tmp.exclude
mkdir -p $tmpRootDir
tmpDir=$( mktemp -d $tmpRootDir/TMP.XXXXXXXXXX ) 

mkdir -p products %STATE

mv products $tmpDir
mv %STATE   $tmpDir

find . -type d -name '*.tardir*' -exec chmod -R 777 {} \; -exec rm -rf {} \; 2>/dev/null
find . -type f -name '*.pyok*'   -exec chmod -R 777 {} \; -exec rm -f  {} \; 2>/dev/null

chmod -R 777 $tmpDir && rm -rf $tmpDir &

