#!/bin/bash 

title1=$(echo $3 | sed 's/ /\\\ /g')
title2=$(echo $5 | sed 's/ /\\\ /g' | sed 's/.*\((.*)\)/\1/g')

file1=$6
file2=$7

res=$(echo $3 | grep "(working copy)$")
if [ $? = 0 ]; then
   file1=$(echo $3 | gawk -F "(working copy)" '{print $1}')
fi

res=$(echo $5 | grep "(working copy)$")
if [ $? = 0 ]; then
   file2=$(echo $5 | sed 's@\(.*\)[[:space:]]\+(working copy)$@\1@')
fi

gvim --nofork -d -geometry 179x85 "$file1" "$file2" +":set titlestring=$title1\\ \\ VS.\\ \\ $title2"

