#!/bin/bash --norc

shortOpt=

if   [ "$1" = "-s" ] || [ -z "$1" ]; then
	[ "$1" = "-s" ] && shortOpt='-sb'; git status $shortOpt; exit 0;
fi

if   [ "$1" = "-ss" ];  then shortOpt=;      shift
elif [ "$1" = "-sss" ]; then shortOpt='-sb';  shift; fi

dirs="$@"
[ -z "$dirs" ] && dirs='$PWD'

for d in $dirs; do
	gss=$(git submodule status --recursive)
	if [ -n "$gss" ]; then
		echo "[0;34m-------------------------------------------------------------------------------- [1m$PWD[0m[0m"
	fi
	git status $shortOpt
	if [ -n "$gss" ]; then
		for sm in $(git submodule status --recursive | awk -F '(' '{print $1}' | awk '{print $2}'); do
			subpath=$PWD/$sm
			echo "[0;34m-------------------------------------------------------------------------------- [1m$subpath[0m[0m"
			cd $subpath; git status $shortOpt; cd - > /dev/null
		done
	fi
done
