#!/bin/bash --norc

#| sed 's@\(.*\)\(rerun\)\(.*\)@\1[0;35m\2[0m\3@g'\
#| sed 's@\(.*\)\(done\)\(.*\)@\1[0;1;32m\2[0;32m\3[0m[0m@g'\

lmake $@ \
| sed 's@\(.*\)\(fail[ed]*\|[Ee]rror\|undefined\)\(.*\)@[0;31m\1[1m\2[0;31m\3[0m@g'\
| sed 's@\(.*\)\([Ww]arning\|WARNING\)\(.*\)@[0;33m\1[1m\2[0;33m\3[0m@g'
