#! /bin/bash --norc

cd /usr/lib/ccache

comps="
arm-none-eabi-c++
arm-none-eabi-g++
arm-none-eabi-gcc
arm-none-eabi-gcc-4.7.4"

for comp in $comps; do
	[ ! -f $comp ] && sudo ln -svf ../../bin/ccache $comp
done

cd -

